# TODO
# general settings
name: train_LIRDehaze
model_type: Origin
manual_seed: 10

num_gpu: 1
gpu_id: 1
pretraining: False

datasets:
  train:
    name: OTS
    type: Dataset_Dehaze
    dataroot_gt: ~
    dataroot_lq: ~
    filename_tmpl: '{}'
    pin_memory: True
    io_backend:
      type: disk

    scale: 1
    use_hflip: True
    use_rot: True
    num_worker_per_gpu: 16
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda

    mini_batch_sizes: [16,8,4]
    iters: [250000, 250000, 250000]
    gt_size: 258
    gt_sizes: [128,160,256]


  val:
    name: SOTS
    type: Dataset_Dehaze
    dataroot_gt: ~
    dataroot_lq: ~
    filename_tmpl: '{}'
    io_backend:
      type: disk
    mod: 32

network_g:
  type: LIR

path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

train:
  total_iter: 750000
  warmup_iter: -1
  ema_decay: 0.999

  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-4
    betas: [ 0.9, 0.999 ]

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [400000, 350000]
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

val:
  val_freq: 4000
  save_img: false

  metrics:
    psnr_y:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: True

    psnr_rgb:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: False

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: False
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500